### ISSUE TITLE
Manual NPM Publish

### ISSUE THREAD

**Issue by achang-ui** [saucelabs/network-viewer#107]
With #101 merged, @farhan-sauce @farhan687, can you trigger a Manual NPM Publish? :pray:

**Comment by farhan687** [comment]
[paweldudzinski](https://github.com/paweldudzinski) can trigger publish action.

**Comment by achang-ui** [comment]
Hey @paweldudzinski, any chance you could do a manual publish soon? Thanks!

**Comment by paweldudzinski** [comment]
@achang-ui new version v1.2.0 is published.

**Comment by achang-ui** [comment]
Hey @paweldudzinski, I don't think it was done correctly. It hasn't been published to the NPM registry.

Can you trigger the same action as this: https://github.com/saucelabs/network-viewer/actions/runs/1319645231

It needs to do a `Publish` and `Release` process.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/100368679/187475156-d48a5800-e22e-424d-93e6-44b1afd3fd59.png">

Thanks!

**Comment by paweldudzinski** [comment]
@achang-ui the pipeline was triggered
