### ISSUE TITLE
Network Viewer Example App Fails to Build

### ISSUE THREAD

**Issue by seanmarpo** [saucelabs/network-viewer#129]
## Expected Behavior
The network-viewer example application successfully builds

## Actual Behavior
The network-viewer example app no longer builds after the latest commit to update dependencies

## Steps to Reproduce the Problem

  1. npm ci && cd examples && npm i && cd .. && npm run build

```
> network-viewer-example@0.0.0 build
> SKIP_PREFLIGHT_CHECK=true node ../node_modules/react-scripts/bin/react-scripts.js build

Creating an optimized production build...
Failed to compile.

[eslint] Failed to load config "react-app" to extend from.
Referenced from: /Users/smarpo/test/network-viewer/examples/package.json


ERROR: "build:examples" exited with 1.
```

## Specifications

  - Version: latest commit
  - Platform: MacOS / Node v18 / Python 3.10.8 (now required after the latest dependency bump)

**Comment by yuyi-sl** [comment]
Thank you for your interest in this project!

We will not be addressing current issues as we are working on a new release now. We are open to receive feedback once the new release is done.

**Comment by rus-99-pk** [comment]
Hello!

@seanmarpo, thank you for your question.

@yuyi-sl, when do you have a plan to release new version? And will it be pack to docker-container?

**Comment by yuyi-sl** [comment]
Hey @seanmarpo and @rus-99-pk ,

executing `npm ci && cd examples && npm i && cd .. && npm run build` should be working now. The issue was one incompatible dependency.

**Comment by seanmarpo** [comment]
Thank you! Tested and the build does work on the `main` branch. You can close this out.
