### ISSUE TITLE
Table is empty when using static data

### ISSUE THREAD

**Issue by snyamathi** [saucelabs/network-viewer#144]
## Expected Behavior

network viewer should show static data when passing a HAR file data directly eg

```jsx
import data from './har.json';
// ...
<NetworkViewer data={data}/>
```

![image](https://github.com/user-attachments/assets/eee7c83d-f503-4b64-85d1-3050076bb540)

## Actual Behavior

The table is blank because the table height is 0

```js
  useEffect(() => {
    if (ref?.current) {
      setTableBodyHeight(ref.current.clientHeight - TABLE_HEADER_HEIGHT);
    }
  }, [ref]);
```

![image](https://github.com/user-attachments/assets/1b0bd38f-b87e-4b26-9377-8b607df35f13)

## Steps to Reproduce the Problem

I have a reproduction here (and possible fix, but feel free to run with that if you like the approach) https://stackblitz.com/github/snyamathi/network-viewer-repro?file=patches%2Fnetwork-viewer%2B2.2.1.patch

When you pass a har file json data to the viewer, the table is always empty because the height is calculated at 0 and not updated when the data loads

## Specifications

  - Version: 2.2.1
  - Platform: N/A
  - Subsystem: N/A

**Comment by yuyi-sl** [comment]
Thank you for the report and investigation!

It should now be working on the most recent master branch and release version.
