### ISSUE TITLE
_blocked_queueing and _queued properties

### ISSUE THREAD

**Issue by Akrabut** [saucelabs/network-viewer#70]
My waterfall column displays nothing because the `startedAt` property is `NaN` as a result of `_blocked_queueing` property being `undefined`.

I generate HAR files using `chrome-har` library and this property seems to be called `_queued` rather than `_blocked_queueing`.
Not sure what's up with this, has the property key name been changed? does this differ??
Does `_blocked_queueing` still exist in some context? if not, I could just PR a fix.

[Relates to this code](https://github.com/saucelabs/network-viewer/blob/2b2f74017fd93d71c7a53a137289e51af6341997/src/utils.js#L268)

**Comment by achang-ui** [comment]
@farhan-sauce @farhan687 Anyway we can merge this PR https://github.com/saucelabs/network-viewer/pull/101 to resolve this issue?

**Comment by achang-ui** [comment]
Thanks @paweldudzinski for merging this PR. What's is next step for getting a new build/release published to the npm registry?

@farhan-sauce Can you trigger a "Manual NPM Publish"?
